spring:
  application:
    name: demo
  output:
    ansi:
      enabled: always
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

# Optional: customize logging pattern to include colors (Spring Boot's default patterns already use ANSI when enabled)
# logging:
#   pattern:
#     console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${spring.application.name}){cyan} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){magenta} : %m%n%wEx"

# DevTools LiveReload and restart settings (use in development only)
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources, src/main/java
    livereload:
      enabled: true

# To enable these only in development, create `application-dev.yml` or run with `-Dspring.profiles.active=dev`.
